### ISSUE TITLE
Bad coding :(

### ISSUE THREAD

**Issue by InvokerMaster** [Saturn-Radius/angularjs-firebase-auth#1]
👎 
Do you know coding :)
@UltaChain

**Comment by Saturn-Radius** [comment]
LOL

**Comment by zygroup1129** [comment]
Very bad coding!
did you started coding yesterday? ;)

**Comment by Saturn-Radius** [comment]
LOL
You started coding one month ago?
Why don't you have any public repository?
You are afraid to make public repository?
